TOP=	..
PROG=	${CL_PROGNAME}
SRCS=	citylife.c				\
			engines/terra_genesis.c



include ${TOP}/Makefile.config
include ${TOP}/mk/build.prog.mk

# Defined in ${TOP}/Makefile.config
CFLAGS+=		-O2 -Wall ${DEBUG_FLAGS}